version: "3"
services:
  db:
    
    image: mysql:5.7
    restart: always
    volumes:
      - ./swap/mysql:/var/lib/mysql
      #- ./sql:/docker-entrypoint-initdb.d/:ro
    ports:
      - "7106:3306"
    environment:
       MYSQL_ROOT_PASSWORD: FdDCas92ARPcKgtx
       MYSQL_DATABASE: iot
       MYSQL_USER: wxd
       MYSQL_PASSWORD: FdDCas92ARPcKgtx
    networks:
      - backend

  redis:
    
    image: redis:4.0
    restart: always
    ports:
      - "7107:6379"
    volumes:
      - ./swap/redis/data:/data/
      - ./swap/redis/etc/redis-password:/run/secrets/redis-password
    environment:
        REDIS_PASS_FILE: /run/secrets/redis-password
    command: [
      "bash", "-c",
      '
       docker-entrypoint.sh
       --requirepass "$$(cat $$REDIS_PASS_FILE)"
      '
    ]
    networks:
      - backend


  mosquitto:
    
    image: vimagick/mosquitto
    ports:
      - "7108:1883"
      - "7109:8080"
    volumes:
      - ./swap/mqtt/mosquitto.conf:/etc/mosquitto/mosquitto.conf
      - ./swap/mqtt/pwfile:/etc/mosquitto/pwfile
      - ./swap/mqtt:/var/lib/mosquitto
    restart: always
    networks:
      - backend

  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    networks:
      - backend
    ports:
        - "7110:7110"

  wechat_token:
    build:
      context: ./wechat_token
      dockerfile: ./Dockerfile
    networks:
      - backend
    ports:
      - "7113:80"
    
  echo:
    build:
      context: ./echo
      dockerfile: ./Dockerfile
    networks:
      - backend
    ports:
      - "7114:80"

  admin:
    build:
      context: ./admin
      dockerfile: ./Dockerfile
    
    networks:
      - backend
    ports:
      - "7111:80"

  wechat_cb:
    build:
      context: ./wechat_cb
      dockerfile: ./Dockerfile
    networks:
      - backend
    ports:
      - "7112:80"
  
networks:
  backend: